using OrthoSpineAI.Domain.Models;
using OrthoSpineAI.Domain.ValueObjects;

namespace OrthoSpineAI.Infrastructure.Devices;

/// <summary>
/// BLE device driver for ORT100 orthometr.
/// Production use: replace SimulateReceiveLoopAsync with P/Invoke to cdortometr.dll.
/// Thread-safe: FrameReceived is raised from background thread; callers must marshal to UI thread.
/// </summary>
public sealed class BleDeviceDriver : IDeviceDriver
{
    private string _macAddress = string.Empty;
    private CancellationTokenSource? _cts;
    private volatile bool _isConnected;
    private bool _disposed;
    private readonly object _lock = new();
    private readonly Random _rng = new();

    // ── Simulator zeroing state (gap #15) ──────────────────────────────────
    // Raw values generated by the last frame tick (before any offset).
    private double _rawRoll;
    private int    _rawWay;
    // Offsets applied to raw values before publishing. Updated by SendConfig
    // based on the OrtResetFlag decoded into DeviceConfig booleans.
    private double _rollOffset;
    private int    _wayOffset;
    // ───────────────────────────────────────────────────────────────────────

    public event EventHandler<DeviceFrame>? FrameReceived;

    public bool IsConnected => _isConnected;

    public string Initialize(string macAddress)
    {
        _macAddress = macAddress;
        // TODO: P/Invoke → CDClientOrtometr.SetMacAddress(_macAddress)
        return string.Empty; // empty = success
    }

    public bool Start(CancellationToken cancellationToken = default)
    {
        lock (_lock)
        {
            if (_isConnected) return true;
            _cts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
            _isConnected = true;
        }
        _ = Task.Run(() => SimulateReceiveLoopAsync(_cts.Token), _cts.Token);
        return true;
    }

    public bool Stop()
    {
        lock (_lock)
        {
            if (!_isConnected) return true;
            _cts?.Cancel();
            _isConnected = false;
        }
        return true;
    }

    public void SendConfig(DeviceConfig config)
    {
        // TODO: P/Invoke → CDClientOrtometr.SendConfig(ref cfgFrame)
        // cfgFrame.mode_set    = (uint)config.Mode
        // cfgFrame.b_zero_angle     = config.ZeroAngle
        // cfgFrame.b_zero_angle_def = config.ZeroAngleDef
        // cfgFrame.b_zero_way       = config.ZeroWay
        // cfgFrame.text_up     = ASCII-padded config.TextUp

        // Simulate OrtResetFlag zeroing behaviour (gap #15):
        // ZeroAngle     → zero roll to the current physical position (offset = raw).
        // ZeroAngleDef  → zero roll to gravity reference (offset = 0, same effect in sim).
        // ZeroWay       → zero distance to current position (offset = raw).
        // Combinations (ZERO_WAY_ANGLE / ZERO_WAY_ANGLE_DEF) apply both.
        lock (_lock)
        {
            if (config.ZeroAngle || config.ZeroAngleDef)
                _rollOffset = _rawRoll;

            if (config.ZeroWay)
                _wayOffset = _rawWay;
        }
    }

    /// <summary>
    /// Simulates 10 Hz BLE frame stream. Replace with real DLL frame decoding.
    /// Raises FrameReceived on background thread — consumers must dispatch to UI thread.
    /// </summary>
    private async Task SimulateReceiveLoopAsync(CancellationToken ct)
    {
        try
        {
            while (!ct.IsCancellationRequested)
            {
                var frame = BuildSimulatedFrame();
                FrameReceived?.Invoke(this, frame);
                await Task.Delay(100, ct); // 10 Hz
            }
        }
        catch (OperationCanceledException) { }
        finally
        {
            _isConnected = false;
        }
    }

    private DeviceFrame BuildSimulatedFrame()
    {
        double rawRoll = Math.Round(_rng.NextDouble() * 90 - 45, 2);
        double tilt    = Math.Round(_rng.NextDouble() * 20 - 10, 2);
        int    rawWay  = _rng.Next(0, 600);

        // Persist raw values under lock so SendConfig can read them for zeroing.
        double appliedRoll;
        int    appliedWay;
        lock (_lock)
        {
            _rawRoll = rawRoll;
            _rawWay  = rawWay;
            appliedRoll = Math.Round(rawRoll - _rollOffset, 2);
            appliedWay  = rawWay - _wayOffset;
        }

        return new DeviceFrame
        {
            Status      = new DeviceStatus(0),
            Signal      = _rng.Next(-90, -40),
            Battery     = 3.7 + _rng.NextDouble() * 0.5,
            Shake       = Math.Round(_rng.NextDouble() * 0.1, 3),
            Roll        = appliedRoll,
            RollOffset  = _rollOffset,
            Tilt        = tilt,
            Way         = appliedWay,
            Space       = 120,
            Force1      = 0,
            Force2      = 0,
            Timestamp   = DateTime.UtcNow
        };
    }

    public void Dispose()
    {
        if (_disposed) return;
        Stop();
        _cts?.Dispose();
        _disposed = true;
        GC.SuppressFinalize(this);
    }
}
