// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrthoSpineAI.Infrastructure.Persistence;

#nullable disable

namespace OrthoSpineAI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510151046_AddMedTestDefinitionKeyFK")]
    partial class AddMedTestDefinitionKeyFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.AwwsResult", b =>
                {
                    b.Property<int>("AwwsResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlRecommendation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupResultsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<int>("MedTestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PilsControlKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PilsVariant")
                        .HasColumnType("INTEGER");

                    b.HasKey("AwwsResultId");

                    b.HasIndex("MedTestId")
                        .IsUnique();

                    b.ToTable("AwwsResults");
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.Clinic", b =>
                {
                    b.Property<int>("ClinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ClinicId");

                    b.ToTable("Clinics", (string)null);
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.MedTest", b =>
                {
                    b.Property<int>("MedTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Beighton")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExaminationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GaitDisturbance")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Growth")
                        .HasColumnType("REAL");

                    b.Property<bool>("KneeValgus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedTestDefinitionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TarsalValgus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TestPP")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("MedTestId");

                    b.HasIndex("MedTestDefinitionKey");

                    b.HasIndex("PatientId");

                    b.HasIndex("SystemUserId");

                    b.ToTable("MedTests", (string)null);
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.MedTestContinuousResult", b =>
                {
                    b.Property<int>("MedTestContinuousResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Battery")
                        .HasColumnType("REAL");

                    b.Property<double>("Force1")
                        .HasColumnType("REAL");

                    b.Property<double>("Force2")
                        .HasColumnType("REAL");

                    b.Property<int>("MedTestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrtMeas")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Roll")
                        .HasColumnType("REAL");

                    b.Property<double>("RollOffset")
                        .HasColumnType("REAL");

                    b.Property<double>("Shake")
                        .HasColumnType("REAL");

                    b.Property<int>("Signal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Space")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tilt")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Way")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedTestContinuousResultId");

                    b.HasIndex("MedTestId");

                    b.ToTable("MedTestContinuousResults", (string)null);
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.MedTestDefinition", b =>
                {
                    b.Property<int>("MedTestDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("MedTestDefinitionId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("MedTestDefinitions", (string)null);
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.MedTestResult", b =>
                {
                    b.Property<int>("MedTestResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedTestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrtMeas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhysicalUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("PhysicalValue")
                        .HasColumnType("REAL");

                    b.Property<int>("Plane")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedTestResultId");

                    b.HasIndex("MedTestId");

                    b.ToTable("MedTestResults", (string)null);
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.MedTestStage", b =>
                {
                    b.Property<int>("MedTestStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyPlaneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MainSurveyControl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MedTestDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OrtContinousMeas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrtMeas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrtMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrtNextStepButton")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrtResetFlag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrtState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Plane")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipControl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("ValueISOM1")
                        .HasColumnType("REAL");

                    b.Property<double?>("ValueISOM3")
                        .HasColumnType("REAL");

                    b.HasKey("MedTestStageId");

                    b.HasIndex("MedTestDefinitionId");

                    b.ToTable("MedTestStages", (string)null);
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressSt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClinicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("PESEL")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.SystemUser", b =>
                {
                    b.Property<int>("SystemUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("SystemUserId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("SystemUsers", (string)null);
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.AwwsResult", b =>
                {
                    b.HasOne("OrthoSpineAI.Domain.Entities.MedTest", "MedTest")
                        .WithOne()
                        .HasForeignKey("OrthoSpineAI.Domain.Entities.AwwsResult", "MedTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedTest");
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.MedTest", b =>
                {
                    b.HasOne("OrthoSpineAI.Domain.Entities.MedTestDefinition", "MedTestDefinition")
                        .WithMany()
                        .HasForeignKey("MedTestDefinitionKey")
                        .HasPrincipalKey("Key")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrthoSpineAI.Domain.Entities.Patient", "Patient")
                        .WithMany("MedTests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrthoSpineAI.Domain.Entities.SystemUser", "SystemUser")
                        .WithMany("MedTests")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedTestDefinition");

                    b.Navigation("Patient");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.MedTestContinuousResult", b =>
                {
                    b.HasOne("OrthoSpineAI.Domain.Entities.MedTest", "MedTest")
                        .WithMany("ContinuousResults")
                        .HasForeignKey("MedTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedTest");
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.MedTestResult", b =>
                {
                    b.HasOne("OrthoSpineAI.Domain.Entities.MedTest", "MedTest")
                        .WithMany("Results")
                        .HasForeignKey("MedTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedTest");
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.MedTestStage", b =>
                {
                    b.HasOne("OrthoSpineAI.Domain.Entities.MedTestDefinition", "MedTestDefinition")
                        .WithMany("Stages")
                        .HasForeignKey("MedTestDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedTestDefinition");
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.Patient", b =>
                {
                    b.HasOne("OrthoSpineAI.Domain.Entities.Clinic", "Clinic")
                        .WithMany("Patients")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.SystemUser", b =>
                {
                    b.HasOne("OrthoSpineAI.Domain.Entities.Clinic", "Clinic")
                        .WithMany("SystemUsers")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.Clinic", b =>
                {
                    b.Navigation("Patients");

                    b.Navigation("SystemUsers");
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.MedTest", b =>
                {
                    b.Navigation("ContinuousResults");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.MedTestDefinition", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.Patient", b =>
                {
                    b.Navigation("MedTests");
                });

            modelBuilder.Entity("OrthoSpineAI.Domain.Entities.SystemUser", b =>
                {
                    b.Navigation("MedTests");
                });
#pragma warning restore 612, 618
        }
    }
}
